### ISSUE TITLE
Simulator crash with keyboard navigation, using direct URL

### ISSUE THREAD

**Issue by OnlineCop** [iTNTPiston/botw-ist#4]
I followed a link where the original URL was **dupl**: [https://dupl.itntpiston.app/?r=...](https://dupl.itntpiston.app/?r=get+1+fire+arrow+1+ancient+arrow+1+bow+300+apple%0Aequip+ancient*arrow%0Abreak+1+slots%0Asave%0Aenter+eventide%0Aget+1+weapon%0Aunequip+weapon%0Areload%0Ashoot+1+arrow%0Asave%0Aclose+game%0Areload), which I changed to the newer **ist**: [https://ist.itntpiston.app/?r=...](https://ist.itntpiston.app/?r=get+1+fire+arrow+1+ancient+arrow+1+bow+300+apple%0Aequip+ancient*arrow%0Abreak+1+slots%0Asave%0Aenter+eventide%0Aget+1+weapon%0Aunequip+weapon%0Areload%0Ashoot+1+arrow%0Asave%0Aclose+game%0Areload).

The **ist** page is marked as READ ONLY, as expected.

On the Simulator page, navigate to step 11: `close game` (either via mouse or keyboard). Using the keyboard, press the DOWN arrow to select step 12: `reload`.

On the old **dupl** site, this would create a blank Step 13; on the **ist** site, this appears to crash the simulator:

> Oops, the simulator crashed. Please let the maintainers know.
> TypeError: Cannot read properties of undefined (reading 'getError')

Note that clicking step 12 with the mouse does not cause the simulator to crash.

**Comment by iTNTPiston** [comment]
Thank you for the feedback. I will investigate.

**Comment by iTNTPiston** [comment]
Not sure what the cause was but I changed how the side panel works and that fixed it

**Comment by iTNTPiston** [comment]
Fixed
